version: '2'
services:
    webstore-app:
        image: webstore
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://webstore-mysql:3306/webstore?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_JEST_URI=http://webstore-elasticsearch:9200
        ports:
            - 8080:8080
    webstore-mysql:
        extends:
            file: mysql.yml
            service: webstore-mysql
    webstore-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: webstore-elasticsearch
